from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.models.project import Project

async def seed_projects(db: AsyncSession):
    projects = ["Client A Redesign", "Internal HR Tool", "AI R&D", "Marketing Campaign Q4"]
    
    for p_name in projects:
        stmt = select(Project).where(Project.name == p_name)
        result = await db.execute(stmt)
        if not result.scalars().first():
            db.add(Project(name=p_name, description="Autogenerated project"))
            
    await db.commit()
    print("Projects seeded.")
