"""Add ReportStatus model

Revision ID: 202609100007
Revises: 202609100006
Create Date: 2026-09-10 16:01:04.578744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202609100007'
down_revision: Union[str, Sequence[str], None] = '202609100006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v1_report_statuses',
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index(op.f('ix_v1_report_statuses_status_name'), 'v1_report_statuses', ['status_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_v1_report_statuses_status_name'), table_name='v1_report_statuses')
    op.drop_table('v1_report_statuses')
    # ### end Alembic commands ###
