"""Add RolePermission model

Revision ID: 202609100004
Revises: 202609100003
Create Date: 2026-09-10 12:10:27.717878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202609100004'
down_revision: Union[str, Sequence[str], None] = '202609100003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v1_role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['v1_permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['v1_roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v1_role_permissions')
    # ### end Alembic commands ###
