"""Add ReportVersion model

Revision ID: 202609100009
Revises: 202609100008
Create Date: 2026-09-10 16:01:08.728603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '202609100009'
down_revision: Union[str, Sequence[str], None] = '202609100008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v1_report_versions',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('manager_comment', sa.String(), nullable=True),
    sa.Column('tasks_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tasks_planned', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hours_worked_by_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optional_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['v1_reports.report_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['v1_report_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v1_report_versions')
    # ### end Alembic commands ###
