"""Add Report model

Revision ID: 202609100008
Revises: 202609100007
Create Date: 2026-09-10 16:01:06.628315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202609100008'
down_revision: Union[str, Sequence[str], None] = '202609100007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v1_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('current_status_id', sa.UUID(), nullable=False),
    sa.Column('current_version_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_status_id'], ['v1_report_statuses.status_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['v1_projects.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['v1_users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v1_reports')
    # ### end Alembic commands ###
