"""Add Permission model

Revision ID: 202609100002
Revises: 202609100001
Create Date: 2026-09-10 12:10:23.163366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202609100002'
down_revision: Union[str, Sequence[str], None] = '202609100001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v1_permissions',
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.Column('permission_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_v1_permissions_permission_name'), 'v1_permissions', ['permission_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_v1_permissions_permission_name'), table_name='v1_permissions')
    op.drop_table('v1_permissions')
    # ### end Alembic commands ###
